name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run chmod to make gradlew executable
        run: chmod +x ./app/gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: app
      - name: Coverage report building
          JACOCO_SOURCE_PATH: app/src/main/java 
        with: ./cc-test-reporter
          format-coverage: target/site/jacoco/jacoco.xml 
          input-type: jacoco
          upload-coverage: ./cc-test-reporter 
